create or replace function exibeGrade(CURSOID integer,GRADE integer)
returns SETOF record GRADE_CURRICULAR as $$
	select 
		CURSO.ID_CURSO, 
		CURSO.NOME,
		NR_GRADE,
		NR_PERIODO,
		DISCIPLINA.ID_DISCIPLINA,
		DISCIPLINA.NOME,
		CARGA_HORARIA,
	from 
		GRADE_CURRICULAR,
		CURSO,
		DISCIPLINA
	WHERE CURSO.ID_CURSO = CURSOID
	AND NR_GRADE = GRADE
	AND CURSO.ID_CURSO = GRADE_CURRICULAR.ID_CURSO
	AND DISCIPLINA.ID_DISCIPLINA = GRADE_CURRICULAR.ID_DISCIPLINA
	
	ORDER BY 
	ID_CURSO,
	NR_GRADE,
	NR_PERIODO;
$$
language sql;

