CREATE ROLE SECRETARIA;
CREATE ROLE PROFESSOR;
CREATE ROLE COORDENADOR;
CREATE ROLE DIRECAO;

-- CRIAND USUARIOS
CREATE ROLE ANDRESSA LOGIN PASSWORD '12345' IN ROLE SECRETARIA;
CREATE ROLE LINA LOGIN PASSWORD '4567' IN ROLE PROFESSOR;

-- RETIRAR PERMISSÕES 
REVOKE ALL ON TABLE PROFESSOR FROM PUBLIC;
REVOKE ALL ON TABLE CURSO FROM PUBLIC;
REVOKE ALL ON TABLE DEPARTAMENTO FROM PUBLIC;
REVOKE ALL ON TABLE DISCIPLINA FROM PUBLIC;
REVOKE ALL ON TABLE GRADE_CURRICULAR FROM PUBLIC;
REVOKE ALL ON TABLE DISCIPLINA_OFERTADA FROM PUBLIC;
REVOKE ALL ON TABLE ALUNO FROM PUBLIC;
REVOKE ALL ON TABLE CONDICAO FROM PUBLIC;
REVOKE ALL ON TABLE HISTORICO FROM PUBLIC;

-- Criação de Função SQL para listar Professores.
CREATE FUNCTION LISTAR_PROFESSORES()
RETURNS SETOF PROFESSOR AS $$
    SELECT ID_PROFESSOR, NOME
    FROM PROFESSOR
    ORDER BY NOME;
$$ LANGUAGE SQL;

REVOKE ALL ON FUNCTION LISTAR_PROFESSORES() FROM PUBLIC;

-- Concedendo privilégio de execução para os ROLEs SECRETARIA,
-- DIRECAO

GRANT EXECUTE ON FUNCTION LISTAR_PROFESSORES() TO SECRETARIA;

GRANT EXECUTE ON FUNCTION LISTAR_PROFESSORES() TO DIRECAO;

GRANT EXECUTE ON FUNCTION LISTAR_PROFESSORES() TO COORDENADOR;

-- Atribuição de privilégios (GRANT) para consulta (SELECT) e inserção
-- (INSERT) sobre as tabelas PROFESSOR, CURSO, DEPARTAMENTO, ALUNO e 
-- CONDICAO para o ROLE SECRETARIA.

GRANT SELECT, INSERT ON PROFESSOR, CURSO, DEPARTAMENTO, ALUNO, CONDICAO TO
SECRETARIA WITH GRANT OPTION;

-- O WITH GRANT OPTION permite que esse usuário (SECRETARIA) não apenas use 
-- os privilégios concedidos, mas também os repasse a outros usuários/roles.


GRANT SELECT, INSERT, UPDATE, DELETE ON CURSO, DISCIPLINA, GRADE_CURRICULAR,
DISCIPLINA_OFERTADA TO COORDENADOR;

GRANT PROFESSOR TO SECRETARIA; 
-- Autoriza SECRETARIA a fazer SET ROLE para PROFESSOR.

-- Remove todos os privilégios (SELECT, INSERT, UPDATE, DELETE) da tabela 
-- PROFESSOR para o PUBLIC (ou seja, para todos os usuários).
-- Só o dono da tabela (neste caso, o postgres) ainda terá acesso.

REVOKE ALL ON TABLE PROFESSOR FROM PUBLIC;

-- O role SECRETARIA deixa de poder inserir registros na tabela ALUNO,
-- mas mantém outros privilégios (como SELECT, se já tiver sido concedido).
REVOKE INSERT ON TABLE ALUNO FROM SECRETARIA;

-- O COORDENADOR poderá continuar lendo (SELECT) e inserindo (INSERT) cursos, 
-- mas não poderá mais atualizar nem excluir registros dessa tabela.
REVOKE UPDATE, DELETE ON TABLE CURSO FROM COORDENADOR;
